[2021-12-14 17:11:41,167][root][ERROR][main.py><module>] ==> CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "../main.py", line 148, in <module>
    model, weights = train(muzero_config, summary_writer, model_path)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1423, in train
    final_weights = _train(model, target_model, latest_model, config, storage, replay_buffer, batch_storage, summary_writer)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1323, in _train
    log_data = update_weights(model, batch, optimizer, replay_buffer, config, scaler, True)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 758, in update_weights
    value, _, policy_logits, hidden_state = model.initial_inference(obs_batch.reshape(batch_size, -1))
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/model.py", line 66, in initial_inference
    state = self.representation(obs)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/config/hanabi_control/model.py", line 287, in representation
    return self._representation(obs_history)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
