[2022-01-27 09:23:50,483][root][ERROR][main.py><module>] ==> model not found at recent/model/model_700000.p
Traceback (most recent call last):
  File "../main.py", line 187, in <module>
    assert os.path.exists(model_path), 'model not found at {}'.format(model_path)
AssertionError: model not found at recent/model/model_700000.p
[2022-01-27 09:31:14,939][root][ERROR][main.py><module>] ==> name 'summary_writer' is not defined
Traceback (most recent call last):
  File "../main.py", line 203, in <module>
    model, weights = test_mcts(muzero_config, summary_writer, model_path)
NameError: name 'summary_writer' is not defined
[2022-01-27 09:32:28,735][root][ERROR][main.py><module>] ==> name 'summary_writer' is not defined
Traceback (most recent call last):
  File "../main.py", line 203, in <module>
    model, weights = test_mcts(muzero_config, summary_writer, model_path)
NameError: name 'summary_writer' is not defined
