[2021-12-02 01:29:18,131][root][ERROR][main.py><module>] ==> Error(s) in loading state_dict for MuZeroNetFull:
	size mismatch for _representation.0.weight: copying a param with shape torch.Size([1024, 3140]) from checkpoint, the shape in current model is torch.Size([1024, 2640]).
Traceback (most recent call last):
  File "../main.py", line 184, in <module>
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cuda')))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MuZeroNetFull:
	size mismatch for _representation.0.weight: copying a param with shape torch.Size([1024, 3140]) from checkpoint, the shape in current model is torch.Size([1024, 2640]).
